# Generated by Django 3.2.6 on 2021-08-29 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('computer_type', models.CharField(choices=[('laptop', 'laptop'), ('tablet', 'tablet'), ('desktop', 'desktop')], default='laptop', max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('disk', models.CharField(max_length=100)),
                ('main_board', models.CharField(max_length=100)),
                ('display_card', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('halt_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
