# Generated by Django 3.2.6 on 2021-08-29 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='publish_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='computer_type',
            new_name='project_type',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='display_card',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='halt_time',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='main_board',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='monitor',
        ),
        migrations.AddField(
            model_name='computer',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
