# Generated by Django 3.2.6 on 2021-08-29 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20210829_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='project_type',
            new_name='computer_type',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='create_time',
            new_name='publish_time',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='update_time',
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.CharField(default='i7', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='disk',
            field=models.CharField(default='500G', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='display_card',
            field=models.CharField(default='sb', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='halt_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='computer',
            name='main_board',
            field=models.CharField(default='marton', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='memory',
            field=models.CharField(default='8G', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.CharField(default='monitore1', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(default='联想电脑1', max_length=100),
        ),
    ]
