# Generated by Django 3.2.6 on 2021-08-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_computer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
